// angular/src/app/financing-calculator/financing-calculator.component.ts
import {Component, HostBinding, input, model} from '@angular/core';

@Component({
  selector: 'app-financing-calculator',
  imports: [],
  templateUrl: './financing-calculator.component.html',
  styleUrl: './financing-calculator.component.css'
})
export class FinancingCalculatorComponent {
  @HostBinding('@state')
  state: 'opened' | 'closed' = 'closed';

  durationMonths = model<number>(2);
  price = model(100);

  increaseDuration() {
    this.durationMonths.set(this.durationMonths()+1);
  }

  decreaseDuration() {
    this.durationMonths.set(this.durationMonths()-1);
  }
}

<div class="wrapper">
  <p>In {{this.durationMonths()}} Monaten bei einer monatlicher Rate von {{(this.price() / this.durationMonths()).toFixed(2)}} EUR
    finanzieren.
    <button (click)="decreaseDuration()">kürzer</button>
    <button (click)="increaseDuration()">länger</button></p>
</div>

// stencil/src/components/financing-calculator/financing-calculator.tsx
import {Component, h, Prop} from "@stencil/core";

@Component({
  tag: "financing-calculator",
  styleUrl: "financing-calculator.css",
  shadow: true
})
export class FinancingCalculatorComponent {
  @Prop() durationMonths: number = 2;
  @Prop() price: number = 100;

  increaseDuration() {
    this.durationMonths++;
  }

  decreaseDuration() {
    this.durationMonths--;
  }

  render() {
    return <div class="wrapper">
      <p>In {this.durationMonths} Monaten bei einer monatlicher Rate von {(this.price / this.durationMonths).toFixed(2)} EUR finanzieren. <button onClick={() => this.decreaseDuration()}>kürzer</button><button onClick={() => this.increaseDuration()}>länger</button></p></div>;
  }
}
