// svelte/src/FinancingCalculator.svelte
<svelte:options tag="financing-calculator" />
<script>
    export let price = 200;
    export let durationMonths = 2;

    const increment = () => {
        durationMonths++
    }
    const decrement = () => {
        durationMonths--
    }

</script>

<div class="wrapper">
    <p>In {durationMonths} Monaten bei einer monatlicher Rate von {(price / durationMonths).toFixed(2)} EUR finanzieren. <button on:click={decrement}>kürzer</button><button  on:click={increment}>länger</button></p></div>



<style>
    .wrapper, p {display: inline-block; margin: 0}
    .wrapper { background-color: deepskyblue; padding: 10px; border-radius: 5px; font-size: 50%; font-weight: 400 }
</style>

// atomico/src/financing-calculator/financing-calculator.tsx
import {c, css, Props, useProp, useState} from "atomico";

function useCounter(prop) {
    const [value, setValue] = useProp(prop);
    return {
        value,
        increment: () => setValue((value) => value + 1),
        decrement: () => setValue((value) => value - 1),
    };
}

function financingCalculator({price}: Props<typeof financingCalculator>) {
    const counter = useCounter("durationMonths");
    return (
        <host shadowDom>
            <div class="wrapper">
                <p>In {counter.value} Monaten bei einer monatlicher Rate von {(price / counter.value).toFixed(2)} EUR
                    finanzieren.
                    <button onclick={counter.decrement}>kürzer</button>
                    <button onclick={counter.increment}>länger</button>
                </p>
            </div>

        </host>
    )
}

financingCalculator.props = {
    durationMonths: {
        type: Number,
        value: 2
    },
    price: {
        type: Number,
        value: 200
    }
}

financingCalculator.styles = css`
    .wrapper, p {
        display: inline-block;
        margin: 0
    }

    .wrapper {
        background-color: deepskyblue;
        padding: 10px;
        border-radius: 5px;
        font-size: 50%;
        font-weight: 400
    }

`

export const FinancingCalculator = c(financingCalculator);
customElements.define('financing-calculator', FinancingCalculator);
