// stencil/src/components/financing-calculator/financing-calculator.tsx
import {Component, h, Prop} from "@stencil/core";

@Component({
  tag: "financing-calculator",
  styleUrl: "financing-calculator.css",
  shadow: true
})
export class FinancingCalculatorComponent {
  @Prop() durationMonths: number = 2;
  @Prop() price: number = 100;

  increaseDuration() {
    this.durationMonths++;
  }

  decreaseDuration() {
    this.durationMonths--;
  }

  render() {
    return <div class="wrapper">
      <p>In {this.durationMonths} Monaten bei einer monatlicher Rate von {(this.price / this.durationMonths).toFixed(2)} EUR finanzieren. <button onClick={() => this.decreaseDuration()}>kürzer</button><button onClick={() => this.increaseDuration()}>länger</button></p></div>;
  }
}

// preact/src/components/FinancingCalculator/FinancingCalculator.tsx
import css from './FinancingCalculator.css?inline';
import {useState} from "react";

export const FinancingCalculator = ({durationMonths = 2, price = 100}) => {
    const [duration, setDuration] = useState(durationMonths);

    function decreaseDuration() {
        setDuration(duration - 1);
    }

    function increaseDuration() {
        setDuration(duration + 1);
    }


    return (
        <>
            <style>
                {css}
            </style>
            <div className="wrapper">
                <p>In {duration} Monaten bei einer monatlicher Rate
                    von {(price / duration).toFixed(2)} EUR finanzieren. <button
                        onClick={() => decreaseDuration()}>kürzer</button>
                    <button onClick={() => increaseDuration()}>länger</button>
                </p>
            </div>
        </>
    );
}
